#!/usr/bin/env bash
#print to infinity and beyond indefinitely
#print I hate the kill command when receiving a SIGTERM signal
#Deletes the file created and terminaes itself  when receiving a SIGQUIT or
#SIGTERM signal

sudo bash -c 'echo $$ > /var/run/myscript.pid'
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done
