#!/usr/bin/env bash
# Displays numbers from 1 to 100.
# print "FizzBuzz" if number is a multiple of 3 and 5
# print "Fizz" if number is multiple of 3
# ptint "Buzz" if number is a multiple of 5
# Otherwise, displays the number, list format

for i in {1..100}
do
if ((i % 15 == 0))
    then
    echo "FizzBuzz"
elif ((i % 5 == 0))
    then
    echo "Buzz"
elif (( i % 3 == 0))
    then
    echo "Fizz"
else
    echo "$i"
fi
done
