#!/usr/bin/env bash
# show the time for 12 hours and 59 minutes
#    print hours from 0 to 12
#    print minutes from 1 to 59

i="0"
while [ $i -le 12 ]
do
echo "Hour: $i"
j="1"
while [ $j -le 59 ]
do
echo "$j"
j=$((j+1))
done
i=$((i+1))
done
