#!/usr/bin/env bash
# Bash script that gives you information about the school file.

file_name="school"

if [ -e "$file_name" ] && [ -d "$file_name" ]; then
  echo "$file_name exists but it’s a directory"
elif [ -e "$file_name" ]; then
  echo "$file_name file exists"
else
  echo "$file_name file does not exist"
fi
