#!/usr/bin/env bash
# Bash script that gives you information about the school file.
file_name="school"

if [ -e "$file_name" ]; then
  if [ -d "$file_name" ]; then
    echo "$file_name exists but it’s a directory"
  else
    echo "$file_name file exists"
  
    if [ -s "$file_name" ]; then
      echo "$file_name file is not empty"
    else
      echo "$file_name file is empty"
    fi

    if [ -f "$file_name" ]; then
      echo "$file_name is a regular file"
    fi
  fi
else
  echo "$file_name file does not exist"
fi
